# Generated by Django 5.0.3 on 2024-06-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='ofrenda',
            field=models.DecimalField(decimal_places=2, default=225, max_digits=10, verbose_name='OFRENDAS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='eventos_participados', to='app.persona', verbose_name='Participantes del Devocional'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='devocional_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_dirigidos', to='app.persona', verbose_name='Director del Devocional'),
        ),
    ]
