# Generated by Django 5.0.3 on 2024-06-21 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_persona_servicio_ofrenda_servicio_participantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='devocional_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_dirigidos', to='app.persona', verbose_name='Director del Cultural'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='eventos_participados', to='app.persona', verbose_name='Participantes del Cultural'),
        ),
    ]
