# Generated by Django 5.0.3 on 2024-06-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_servicio_cultural'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='hora',
        ),
    ]
