# Generated by Django 5.0.3 on 2024-06-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_servicio_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='ofrenda',
            field=models.CharField(max_length=13, verbose_name='OFRENDA'),
        ),
    ]
