# Generated by Django 5.0.3 on 2024-06-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_servicio_ofrenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='devocional_1',
            new_name='cultural_1',
        ),
        migrations.AddField(
            model_name='servicio',
            name='devocional',
            field=models.TextField(default=2020, max_length=50, verbose_name='DEVOCIONAL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='DIRECCION DEL CULTO DE ALTAR'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='lectura',
            field=models.TextField(max_length=50, verbose_name='LECTURA DE LA PALABRAS'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='mensaje',
            field=models.TextField(max_length=50, verbose_name='MENSAJE DE LAS PALABRAS'),
        ),
    ]
